language: python
matrix:
  include:
    - os: linux
      sudo: required
      python: 3.5
      env: TOXENV=py35
    - os: linux
      sudo: required
      python: 3.6
      env: TOXENV=py36
    - os: linux
      sudo: required
      python: 3.7
      env: TOXENV=py37

install: pip install docutils tox
script: tox
